[package]
name = "icedgui"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.3"
iced_native = "0.4.0"
iced_graphics = "0.2.0"